services:
  cmmc-prod:
    container_name: cmmc-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - cmmc-prod-data:/data

volumes:
  cmmc-prod-data:
