services:
  cmmc-prod:
    container_name: cmmc-prod
    build:
      context: ./cmmc-mao
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - cmmc-prod-data:/data
    environment:
      - CM_DATA:/data
      - AUTH_SECRET:${AUTH_SECRET}

volumes:
  cmmc-prod-data:
