services:
  cmmc-dev:
    container_name: cmmc-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - cmmc-dev-data:/data
    ports:
      - "3000:3000"
    environment:
      CM_DATA:/data

volumes:
  cmmc-dev-data:
