services:
  cmmc-dev:
    container_name: cmmc-dev
    build:
      context: ./cmmc-map
      dockerfile: Dockerfile.dev
    volumes:
      - ./cmmc-map:/app
      - /app/node_modules
      - cmmc-dev-data:/data
    ports:
      - "3000:3000"
    environment:
      - CM_DATA:/data
      - AUTH_SECRET:${AUTH_SECRET}
      - AUTH_AZURE_AD_ID:${AUTH_AZURE_AD_ID}
      - AUTH_AZURE_AD_SECRET:${AUTH_AZURE_AD_SECRET}
      - AUTH_AZURE_AD_TENANT_ID:${AUTH_AZURE_AD_TENANT_ID}

volumes:
  cmmc-dev-data:
