# Generated by Django 5.0.3 on 2024-04-24 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('started', models.DateTimeField(null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment_Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('link', models.URLField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment_Objective_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.assessment')),
                ('assessment_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.assessment_objective')),
            ],
        ),
        migrations.AddField(
            model_name='assessment_objective',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.control'),
        ),
        migrations.CreateModel(
            name='EvidenceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidences', models.ManyToManyField(to='policies.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_description', models.TextField(null=True)),
                ('plan_description', models.TextField(null=True)),
                ('na_description', models.TextField(null=True)),
                ('implementation_status', models.PositiveSmallIntegerField(default=0)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.control')),
                ('evidence_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.evidencelist')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment_Policy_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.assessment')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.policy')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=36, unique=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('system_name', models.CharField(blank=True, max_length=255, null=True)),
                ('system_category', models.CharField(blank=True, max_length=255, null=True)),
                ('system_unique_id', models.CharField(blank=True, max_length=255, null=True)),
                ('responsible_org_name', models.CharField(blank=True, max_length=255, null=True)),
                ('responsible_org_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('responsible_org_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('info_owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('info_owner_title', models.CharField(blank=True, max_length=255, null=True)),
                ('info_owner_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('info_owner_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('info_owner_email', models.CharField(blank=True, max_length=255, null=True)),
                ('sys_owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sys_owner_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sys_owner_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('sys_owner_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('sys_owner_email', models.CharField(blank=True, max_length=255, null=True)),
                ('sys_sec_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sys_sec_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sys_sec_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('sys_sec_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('sys_sec_email', models.CharField(blank=True, max_length=255, null=True)),
                ('system_description', models.TextField(blank=True, null=True)),
                ('num_end_users', models.PositiveIntegerField(blank=True, null=True)),
                ('num_admin_users', models.PositiveIntegerField(blank=True, null=True)),
                ('hardsoft_main', models.TextField(blank=True, null=True)),
                ('hardware_listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions_for_hardware_listing', to='policies.evidencelist')),
                ('information_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions_for_information_description', to='policies.evidencelist')),
                ('software_listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions_for_software_listing', to='policies.evidencelist')),
                ('system_top_evi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions_for_system_top_evi', to='policies.evidencelist')),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.revision'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.revision'),
        ),
        migrations.AddField(
            model_name='control',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.section'),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('name', 'revision')},
        ),
    ]
