# Generated by Django 5.0.1 on 2024-03-06 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('started', models.DateTimeField(null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment_Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=3)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Major_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment_Objective_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.assessment')),
                ('assessment_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.assessment_objective')),
            ],
        ),
        migrations.CreateModel(
            name='Minor_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=30)),
                ('brief_description', models.TextField()),
                ('examine', models.TextField()),
                ('interview', models.TextField()),
                ('test', models.TextField()),
                ('detailed_description', models.TextField()),
                ('further_discussion', models.TextField()),
                ('major_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.major_section')),
            ],
        ),
        migrations.AddField(
            model_name='assessment_objective',
            name='minor_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.minor_section'),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('implementation_status', models.CharField(default='N', max_length=2)),
                ('minor_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.minor_section')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.revision')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('file', models.FileField(null=True, upload_to='')),
                ('link', models.URLField(null=True)),
                ('description', models.TextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.policy')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.revision'),
        ),
    ]
