# Generated by Django 5.0.1 on 2024-03-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='version',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('name', 'revision')},
        ),
    ]
