# Generated by Django 5.0.1 on 2024-03-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='description',
            new_name='implementation_description',
        ),
        migrations.AddField(
            model_name='policy',
            name='na_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_description',
            field=models.TextField(null=True),
        ),
    ]
