# Generated by Django 5.0.1 on 2024-03-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_rename_description_policy_implementation_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='implementation_description',
            new_name='plan_description',
        ),
    ]
