# Generated by Django 5.0.3 on 2024-03-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_rename_implementation_description_policy_plan_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='image',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='policy',
        ),
        migrations.AddField(
            model_name='evidence',
            name='policy',
            field=models.ManyToManyField(to='policies.policy'),
        ),
    ]
