# Generated by Django 5.0.3 on 2024-04-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_remove_evidence_image_remove_evidence_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='info_owner_addr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='info_owner_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='info_owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='info_owner_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='info_owner_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='information_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='num_admin_users',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='num_end_users',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='responsible_org_addr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='responsible_org_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='responsible_org_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='sys_owner_addr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='sys_owner_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='sys_owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='sys_owner_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='sys_owner_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='sys_sec_addr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='sys_sec_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='sys_sec_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='sys_sec_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='sys_sec_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='system_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='system_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='system_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='system_unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
